version: "3"
services:
  db:
    image: mysql:8.0.19
    container_name: mysql_container
    ports:
      - "3306:3306"
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/db/data:/var/lib/mysql
    command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'

  app:
    image: bot_app
    build: .
    container_name: bot_app
    networks: 
      - app-net
    volumes:
      - .:/bot
      - /bot/dist
      - /bot/node_modules
    depends_on: 
      - db
    tty: true

networks: 
  app-net:
    driver: bridge