version: "3"
services:
  db:
    image: mysql:8.0.19
    container_name: mysql_container
    ports:
      - "3306:3306"
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    image: bot_app
    build: .
    container_name: bot_app
    networks: 
      - app-net
    depends_on: 
      - db
    tty: true

networks: 
  app-net:
    driver: bridge